server:
  port: 8090

spring:
  #配置数据源
  datasource:
    #配置数据库四大件
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123

#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#spring集成Mybatis环境
#实体类别名扫描包
mybatis:
  type-aliases-package: cn.com.djin.springboot.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #配置日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
